module.exports = {
    option1: ["Good", "Bad", "Very Bad"],
    option2: ["None", "Good", "Bad"],
    option3: ["Vacated", "Nights at Home", "Nights and Days at Home"],
    option4: ["Yes", "No"],
    option5: ["None", "Partial", "All Round"],
    option6: ["None", "Basic", "Standard", "Premium"],
    option7: ["None", "Small", "Large"],
    option8: ["None", "MDF Hollow", "MDF Solid", "Pine Panelled", "Other"],
    option9: ["Owner", "Basic", "Standard", "Premium"],
    option10: ['None or Existing','Carpet','Vynil','Tiles','Timber Overlay','Other'],
    option11: ['None','Paint','Other'],
    option12: ['None','Paint','Tilled Fully','Other'],
    option13: ['None','Existing','Relocated','New Electric Cylinder','New Gas Infinity','Other'],
    option14: ['None','Existing','Relocated','New Small','New Large','Other'],
    option15: ['Owner', 'Subcontractor'],
    option16: ['None', 'Pine 100x25', 'Pine 150x25', 'Fibre Cement', 'Other'],
    option17: ['None', 'Aluminium', 'Pine', 'Cedar', 'uPVC'],
    option18: ['Corrugated', 'Trapezoidal', 'Membrane', 'Mansonry Tile', 'Metal Tile','Other'],
    option19: ['None', 'Plastic', 'Steel', 'Cooper'],
    option20: ['Classic', 'Quad', 'Box', 'Other'],
    option21: ['Round80', 'Round60', 'Rectangle'],
    option22: ['None', 'Pine 150x25', 'Pine 200x25', 'Cedar 150x25', 'Cedar 200x25','Metal 136', 'Metal 150', 'Metal 180'],
    option23: ['None', 'Pine', 'Hardwood', 'Other'],
    option24: ['None', 'Timber', 'Glass', 'Other'],
    option25: ['None', 'Concrete', 'Cobbles'],
    option26: ['None', 'Timber Paling', 'Other'],
}

